# searches stored in the search folder
@searches = [
#    'Padilla.Trust-And-Safety.10',
    'APG.1',
    'Magnum.1',
]

# 
BlackStack::CSVIndexer.add_indexation({
    :name => 'ix.linkedin_url.us.01',
    :description => 'Find the email address, first name, last name, company, industry and location of US LinkedIn users from their URL.',
    :input => './sources/li/Data-with-Country1/united-states/business_email_united_states/business_email_united_states_*.csv',
    :output => './indexes/',
    :log => './logs/',
    :keys => [:linkedin_url],
    :mapping => {
        :first_name => 0,
        :last_name => 1,
        :linkedin_url => 2,
        :facebook_url => 3,
        :twitter_url => 4,
        :email1 => 5,
        :phone1 => 6,
        :industry => 7,
        :job_title => 8,
        :company_name => 9,
        :company_domain => 10,
        :company_headcount => 11,
        :company_industry => 12,
        :company_linkedin_url => 13,
        :company_facebook_url => 14,
        :company_twitter_url => 15,
        :location => 25,
        :phone2 => 34,
        :email2 => 35,
    },
})

BlackStack::CSVIndexer.add_indexation({
    :name => 'ix.linkedin_url.us.02',
    :description => 'Find the email address, first name, last name, company, industry and location of US LinkedIn users from their URL.',
    :input => './sources/li/Data-with-Country1/united-states/business_email_united_states/business_unitedstate_10*.csv',
    :output => './indexes/',
    :log => './logs/',
    :keys => [:linkedin_url],
    :mapping => {
        :first_name => 0,
        :last_name => 1,
        :linkedin_url => 2,
        :facebook_url => 3,
        :twitter_url => 4,
        :email1 => 5,
        :phone1 => 6,
        :industry => 7,
        :job_title => 8,
        :company_name => 9,
        :company_domain => 10,
        :company_headcount => 11,
        :company_industry => 12,
        :company_linkedin_url => 13,
        :company_facebook_url => 14,
        :company_twitter_url => 15,
        :location => 25,
        :phone2 => 34,
        :email2 => 35,
    },
})

BlackStack::CSVIndexer.add_indexation({
    :name => 'ix.linkedin_url.us.03',
    :description => 'Find the email address, first name, last name, company, industry and location of US LinkedIn users from their URL.',
    :input => './sources/li/Data-with-Country1/united-states/business_email_united_states/business_unitedstate_1-*.csv',
    :output => './indexes/',
    :log => './logs/',
    :keys => [:linkedin_url],
    :mapping => {
        :first_name => 0,
        :last_name => 1,
        :linkedin_url => 2,
        :facebook_url => 3,
        :twitter_url => 4,
        :email1 => 5,
        :phone1 => 6,
        :industry => 7,
        :job_title => 8,
        :company_name => 10,
        :company_domain => 11,
        :company_headcount => 12,
        :company_industry => 13,
        :company_linkedin_url => 14,
        :company_facebook_url => 15,
        :company_twitter_url => 16,
        :location => 26,
        :phone2 => 35,
        :email2 => 36,
    },
})

BlackStack::CSVIndexer.add_indexation({
    :name => 'ix.linkedin_url.us.04',
    :description => 'Find the email address, first name, last name, company, industry and location of US LinkedIn users from their URL.',
    :input => './sources/li/Data-with-Country1/united-states/personal_email_united_states/personal_email_united_states-*.csv',
    :output => './indexes/',
    :log => './logs/',
    :keys => [:linkedin_url],
    :mapping => {
        :first_name => 0,
        :last_name => 1,
        :linkedin_url => 2,
        :facebook_url => 3,
        :twitter_url => 4,
        :email1 => 5,
        :phone1 => 6,
        :industry => 7,
        :job_title => 8,
        :company_name => 9,
        :company_domain => 10,
        :company_headcount => 11,
        :company_industry => 12,
        :company_linkedin_url => 13,
        :company_facebook_url => 14,
        :company_twitter_url => 15,
        :location => 25,
        :phone2 => 34,
        :email2 => 35,
    },
})

BlackStack::CSVIndexer.add_indexation({
    :name => 'ix.linkedin_url.us.05',
    :description => 'Find the email address, first name, last name, company, industry and location of US LinkedIn users from their URL.',
    :input => './sources/li/Data-with-Country1/united-states/personal_email_united_states/personal_unitedstate_10*.csv',
    :output => './indexes/',
    :log => './logs/',
    :keys => [:linkedin_url],
    :mapping => {
        :first_name => 0,
        :last_name => 1,
        :linkedin_url => 2,
        :facebook_url => 3,
        :twitter_url => 4,
        :email1 => 5,
        :phone1 => 6,
        :industry => 7,
        :job_title => 8,
        :company_name => 9,
        :company_domain => 10,
        :company_headcount => 11,
        :company_industry => 12,
        :company_linkedin_url => 13,
        :company_facebook_url => 14,
        :company_twitter_url => 15,
        :location => 25,
        :phone2 => 34,
        :email2 => 35,
    },
})

BlackStack::CSVIndexer.add_indexation({
    :name => 'ix.linkedin_url.us.06',
    :description => 'Find the email address, first name, last name, company, industry and location of US LinkedIn users from their URL.',
    :input => './sources/li/Data-with-Country1/united-states/personal_email_united_states/personal_unitedstate_1-*.csv',
    :output => './indexes/',
    :log => './logs/',
    :keys => [:linkedin_url],
    :mapping => {
        :first_name => 0,
        :last_name => 1,
        :linkedin_url => 2,
        :facebook_url => 3,
        :twitter_url => 4,
        :email1 => 5,
        :phone1 => 6,
        :industry => 7,
        :job_title => 8,
        :company_name => 10,
        :company_domain => 11,
        :company_headcount => 12,
        :company_industry => 13,
        :company_linkedin_url => 14,
        :company_facebook_url => 15,
        :company_twitter_url => 16,
        :location => 26,
        :phone2 => 35,
        :email2 => 36,
    },
})

=begin
BlackStack::CSVIndexer.add_indexation({
    :name => 'ix.linkedin_url.uk',
    :description => 'Find the email address, first name, last name, company, industry and location of UK LinkedIn users from their URL.',
    :input => './sources/li/Data-with-Country1/united-kingdom/*.csv',
    :output => './indexes/',
    :log => './logs/',
    :keys => [:linkedin_url],
    :mapping => {
        :first_name => 0,
        :last_name => 1,
        :linkedin_url => 2,
        :facebook_url => 3,
        :twitter_url => 4,
        :email1 => 5,
        :phone1 => 6,
        :industry => 7,
        :job_title => 8,
        :company_name => 9,
        :company_domain => 10,
        :company_headcount => 11,
        :company_industry => 12,
        :company_linkedin_url => 13,
        :company_facebook_url => 14,
        :company_twitter_url => 15,
        :location => 25,
        :phone2 => 34,
        :email2 => 35,
    },
})

BlackStack::CSVIndexer.add_indexation({
    :name => 'ix.linkedin_url.ca',
    :description => 'Find the email address, first name, last name, company, industry and location of UK LinkedIn users from their URL.',
    :input => './sources/li/Data-with-Country1/canada/*.csv',
    :output => './sources/indexes/',
    :log => './sources/logs/',
    :keys => [:linkedin_url],
    :mapping => {
        :first_name => 0,
        :last_name => 1,
        :linkedin_url => 2,
        :facebook_url => 3,
        :twitter_url => 4,
        :email1 => 5,
        :phone1 => 6,
        :industry => 7,
        :job_title => 8,
        :company_name => 9,
        :company_domain => 10,
        :company_headcount => 11,
        :company_industry => 12,
        :company_linkedin_url => 13,
        :company_facebook_url => 14,
        :company_twitter_url => 15,
        :location => 25,
        :phone2 => 34,
        :email2 => 35,
    },
})
=end

BlackStack::CSVIndexer.add_indexation({
    :name => 'ix.linkedin_url.us.09',
    :description => 'Find the email address, first name, last name, company, industry and location of LinkedIn users from their URL, searching into the ZI database.',
    :input => './sources/zi/*.csv',
    :output => './indexes/',
    :log => './logs/',
    :keys => [:linkedin_url],
    :mapping => {
        :first_name => 0,
        :last_name => 1,
        :email => 2,
        :job_title => 4,
        :seniority => 5,
        :department => 6,
        :phone => 7,
        :linkedin_url => 8,
        :state => 10,
        :company_name => 11,
        :company_domain => 12,
        :company_phone => 13,
        :industry => 14,
        :sic => 15,
        :company_linkedin_url => 22,
        :company_revenue => 23,
        :company_headcount => 24, 
    },
})

# ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

BlackStack::CSVIndexer.add_indexation({
    :name => 'ix.persona.us.01',
    :description => 'Find the email address, first name, last name, company, industry and location of US LinkedIn users from their URL.',
    :input => './sources/li/Data-with-Country1/united-states/business_email_united_states/business_email_united_states_*.csv',
    :output => './indexes/',
    :log => './logs/',
    :keys => [:company_name, :first_name, :last_name],
    :mapping => {
        :first_name => 0,
        :last_name => 1,
        :linkedin_url => 2,
        :facebook_url => 3,
        :twitter_url => 4,
        :email1 => 5,
        :phone1 => 6,
        :industry => 7,
        :job_title => 8,
        :company_name => 9,
        :company_domain => 10,
        :company_headcount => 11,
        :company_industry => 12,
        :company_linkedin_url => 13,
        :company_facebook_url => 14,
        :company_twitter_url => 15,
        :location => 25,
        :phone2 => 34,
        :email2 => 35,
    },
})

BlackStack::CSVIndexer.add_indexation({
    :name => 'ix.persona.us.02',
    :description => 'Find the email address, first name, last name, company, industry and location of US LinkedIn users from their URL.',
    :input => './sources/li/Data-with-Country1/united-states/business_email_united_states/business_unitedstate_10*.csv',
    :output => './indexes/',
    :log => './logs/',
    :keys => [:company_name, :first_name, :last_name],
    :mapping => {
        :first_name => 0,
        :last_name => 1,
        :linkedin_url => 2,
        :facebook_url => 3,
        :twitter_url => 4,
        :email1 => 5,
        :phone1 => 6,
        :industry => 7,
        :job_title => 8,
        :company_name => 9,
        :company_domain => 10,
        :company_headcount => 11,
        :company_industry => 12,
        :company_linkedin_url => 13,
        :company_facebook_url => 14,
        :company_twitter_url => 15,
        :location => 25,
        :phone2 => 34,
        :email2 => 35,
    },
})

BlackStack::CSVIndexer.add_indexation({
    :name => 'ix.persona.us.03',
    :description => 'Find the email address, first name, last name, company, industry and location of US LinkedIn users from their URL.',
    :input => './sources/li/Data-with-Country1/united-states/business_email_united_states/business_unitedstate_1-*.csv',
    :output => './indexes/',
    :log => './logs/',
    :keys => [:company_name, :first_name, :last_name],
    :mapping => {
        :first_name => 0,
        :last_name => 1,
        :linkedin_url => 2,
        :facebook_url => 3,
        :twitter_url => 4,
        :email1 => 5,
        :phone1 => 6,
        :industry => 7,
        :job_title => 8,
        :company_name => 10,
        :company_domain => 11,
        :company_headcount => 12,
        :company_industry => 13,
        :company_linkedin_url => 14,
        :company_facebook_url => 15,
        :company_twitter_url => 16,
        :location => 26,
        :phone2 => 35,
        :email2 => 36,
    },
})

BlackStack::CSVIndexer.add_indexation({
    :name => 'ix.persona.us.04',
    :description => 'Find the email address, first name, last name, company, industry and location of US LinkedIn users from their URL.',
    :input => './sources/li/Data-with-Country1/united-states/personal_email_united_states/personal_email_united_states-*.csv',
    :output => './indexes/',
    :log => './logs/',
    :keys => [:company_name, :first_name, :last_name],
    :mapping => {
        :first_name => 0,
        :last_name => 1,
        :linkedin_url => 2,
        :facebook_url => 3,
        :twitter_url => 4,
        :email1 => 5,
        :phone1 => 6,
        :industry => 7,
        :job_title => 8,
        :company_name => 9,
        :company_domain => 10,
        :company_headcount => 11,
        :company_industry => 12,
        :company_linkedin_url => 13,
        :company_facebook_url => 14,
        :company_twitter_url => 15,
        :location => 25,
        :phone2 => 34,
        :email2 => 35,
    },
})

BlackStack::CSVIndexer.add_indexation({
    :name => 'ix.persona.us.05',
    :description => 'Find the email address, first name, last name, company, industry and location of US LinkedIn users from their URL.',
    :input => './sources/li/Data-with-Country1/united-states/personal_email_united_states/personal_unitedstate_10*.csv',
    :output => './indexes/',
    :log => './logs/',
    :keys => [:company_name, :first_name, :last_name],
    :mapping => {
        :first_name => 0,
        :last_name => 1,
        :linkedin_url => 2,
        :facebook_url => 3,
        :twitter_url => 4,
        :email1 => 5,
        :phone1 => 6,
        :industry => 7,
        :job_title => 8,
        :company_name => 9,
        :company_domain => 10,
        :company_headcount => 11,
        :company_industry => 12,
        :company_linkedin_url => 13,
        :company_facebook_url => 14,
        :company_twitter_url => 15,
        :location => 25,
        :phone2 => 34,
        :email2 => 35,
    },
})

BlackStack::CSVIndexer.add_indexation({
    :name => 'ix.persona.us.06',
    :description => 'Find the email address, first name, last name, company, industry and location of US LinkedIn users from their URL.',
    :input => './sources/li/Data-with-Country1/united-states/personal_email_united_states/personal_unitedstate_1-*.csv',
    :output => './indexes/',
    :log => './logs/',
    :keys => [:company_name, :first_name, :last_name],
    :mapping => {
        :first_name => 0,
        :last_name => 1,
        :linkedin_url => 2,
        :facebook_url => 3,
        :twitter_url => 4,
        :email1 => 5,
        :phone1 => 6,
        :industry => 7,
        :job_title => 8,
        :company_name => 10,
        :company_domain => 11,
        :company_headcount => 12,
        :company_industry => 13,
        :company_linkedin_url => 14,
        :company_facebook_url => 15,
        :company_twitter_url => 16,
        :location => 26,
        :phone2 => 35,
        :email2 => 36,
    },
})

=begin
BlackStack::CSVIndexer.add_indexation({
    :name => 'ix.linkedin_url.uk',
    :description => 'Find the email address, first name, last name, company, industry and location of UK LinkedIn users from their URL.',
    :input => './sources/li/Data-with-Country1/united-kingdom/*.csv',
    :output => './indexes/',
    :log => './logs/',
    :keys => [:linkedin_url],
    :mapping => {
        :first_name => 0,
        :last_name => 1,
        :linkedin_url => 2,
        :facebook_url => 3,
        :twitter_url => 4,
        :email1 => 5,
        :phone1 => 6,
        :industry => 7,
        :job_title => 8,
        :company_name => 9,
        :company_domain => 10,
        :company_headcount => 11,
        :company_industry => 12,
        :company_linkedin_url => 13,
        :company_facebook_url => 14,
        :company_twitter_url => 15,
        :location => 25,
        :phone2 => 34,
        :email2 => 35,
    },
})

BlackStack::CSVIndexer.add_indexation({
    :name => 'ix.linkedin_url.ca',
    :description => 'Find the email address, first name, last name, company, industry and location of UK LinkedIn users from their URL.',
    :input => './sources/li/Data-with-Country1/canada/*.csv',
    :output => './sources/indexes/',
    :log => './sources/logs/',
    :keys => [:linkedin_url],
    :mapping => {
        :first_name => 0,
        :last_name => 1,
        :linkedin_url => 2,
        :facebook_url => 3,
        :twitter_url => 4,
        :email1 => 5,
        :phone1 => 6,
        :industry => 7,
        :job_title => 8,
        :company_name => 9,
        :company_domain => 10,
        :company_headcount => 11,
        :company_industry => 12,
        :company_linkedin_url => 13,
        :company_facebook_url => 14,
        :company_twitter_url => 15,
        :location => 25,
        :phone2 => 34,
        :email2 => 35,
    },
})
=end

BlackStack::CSVIndexer.add_indexation({
    :name => 'ix.persona.us.09',
    :description => 'Find the email address, first name, last name, company, industry and location of any person from their company name, first name and last name; into the ZI database.',
    :input => './sources/zi/*.csv',
    :output => './indexes/',
    :log => './logs/',
    :keys => [:company_name, :first_name, :last_name],
    :mapping => {
        :first_name => 0,
        :last_name => 1,
        :email => 2,
        :job_title => 4,
        :seniority => 5,
        :department => 6,
        :phone => 7,
        :linkedin_url => 8,
        :state => 10,
        :company_name => 11,
        :company_domain => 12,
        :company_phone => 13,
        :industry => 14,
        :sic => 15,
        :company_linkedin_url => 22,
        :company_revenue => 23,
        :company_headcount => 24, 
    },
})