BlackStack::CSVIndexer.add_indexation({
    :name => 'ix.linkedin_url.us.01',
    :description => 'Find the email address, first name, last name, company, industry and location of US LinkedIn users from their URL.',
    :input => './sources/li/Data-with-Country1/united-states/business_email_united_states/*.csv',
    :output => './indexes/',
    :log => './logs/',
    :keys => [:linkedin_url],
    :mapping => {
        :first_name => 0,
        :last_name => 1,
        :linkedin_url => 2,
        :facebook_url => 3,
        :twitter_url => 4,
        :email1 => 5,
        :phone1 => 6,
        :industry => 7,
        :job_title => 8,
        :company_name => 9,
        :company_domain => 10,
        :company_headcount => 11,
        :company_industry => 12,
        :company_linkedin_url => 13,
        :company_facebook_url => 14,
        :company_twitter_url => 15,
        :location => 25,
        :phone2 => 34,
        :email2 => 35,
    },
})

BlackStack::CSVIndexer.add_indexation({
    :name => 'ix.linkedin_url.us.02',
    :description => 'Find the email address, first name, last name, company, industry and location of US LinkedIn users from their URL.',
    :input => './sources/li/Data-with-Country1/united-states/personal_email_united_states/*.csv',
    :output => './indexes/',
    :log => './logs/',
    :keys => [:linkedin_url],
    :mapping => {
        :first_name => 0,
        :last_name => 1,
        :linkedin_url => 2,
        :facebook_url => 3,
        :twitter_url => 4,
        :email1 => 5,
        :phone1 => 6,
        :industry => 7,
        :job_title => 8,
        :company_name => 9,
        :company_domain => 10,
        :company_headcount => 11,
        :company_industry => 12,
        :company_linkedin_url => 13,
        :company_facebook_url => 14,
        :company_twitter_url => 15,
        :location => 25,
        :phone2 => 34,
        :email2 => 35,
    },
})

BlackStack::CSVIndexer.add_indexation({
    :name => 'ix.linkedin_url.uk',
    :description => 'Find the email address, first name, last name, company, industry and location of UK LinkedIn users from their URL.',
    :input => './sources/li/Data-with-Country1/united-kingdom/*.csv',
    :output => './indexes/',
    :log => './logs/',
    :keys => [:linkedin_url],
    :mapping => {
        :first_name => 0,
        :last_name => 1,
        :linkedin_url => 2,
        :facebook_url => 3,
        :twitter_url => 4,
        :email1 => 5,
        :phone1 => 6,
        :industry => 7,
        :job_title => 8,
        :company_name => 9,
        :company_domain => 10,
        :company_headcount => 11,
        :company_industry => 12,
        :company_linkedin_url => 13,
        :company_facebook_url => 14,
        :company_twitter_url => 15,
        :location => 25,
        :phone2 => 34,
        :email2 => 35,
    },
})

BlackStack::CSVIndexer.add_indexation({
    :name => 'ix.linkedin_url.ca',
    :description => 'Find the email address, first name, last name, company, industry and location of UK LinkedIn users from their URL.',
    :input => './sources/li/Data-with-Country1/canada/*.csv',
    :output => './sources/indexes/',
    :log => './sources/logs/',
    :keys => [:linkedin_url],
    :mapping => {
        :first_name => 0,
        :last_name => 1,
        :linkedin_url => 2,
        :facebook_url => 3,
        :twitter_url => 4,
        :email1 => 5,
        :phone1 => 6,
        :industry => 7,
        :job_title => 8,
        :company_name => 9,
        :company_domain => 10,
        :company_headcount => 11,
        :company_industry => 12,
        :company_linkedin_url => 13,
        :company_facebook_url => 14,
        :company_twitter_url => 15,
        :location => 25,
        :phone2 => 34,
        :email2 => 35,
    },
})